{% set name = "striprtf" %}
{% set version = "0.0.26" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/striprtf-{{ version }}.tar.gz
  sha256: fdb2bba7ac440072d1c41eab50d8d74ae88f60a8b6575c6e2c7805dc462093aa

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6

test:
  imports:
    - striprtf
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/joshy/striprtf
  summary: A simple library to convert rtf to text
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
